[package]
name = "blogenius"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
comrak = "0.22.0"
handlebars = "5.1.2"
indoc = "2.0.5"
