name: ci
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable 

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check
